language: node_js
node_js:
  - "11"

notifications:
  email: false

cache: npm

install:
  - (cd website && npm install)

script:
  - (cd website && npm run format:test)
  - (cd website && npm run build)

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: website/build/website
  fqdn: gotify.net
  on:
    branch: master